name: Construit et déploie le site Jekyll sur les pages GitHub

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}$
